### PR TITLE
Fix missing join() when building the query string in getGuildBans

### PR DESCRIPTION
**Pull request by Zoddo**

### CODE REVIEW

**Comment by Zoddo** [comment]
Actually, pagination on this endpoint seems to be broken since it was implemented (it throws a 404). When setting the `limit` and `after` parameters, the request actually being sent, as seen by my outbound proxy, is:
`GET /api/v10/guilds/566680007112654859/bans%3Flimit=1000,&after=0?undefined=undefined`

Looking into the `requestHandler.request()` method, it seems that query strings are expected to be passed using the `data` parameter, instead of being set directly in the URI.

That's actually how the `channel.getChannelMessages()` method works:
https://github.com/DasWolke/SnowTransfer/blob/3187caf54df0c1c1b4cc9e03ba8d31c059b0947a/src/methods/Channels.ts#L114-L127

...vs `guild.getGuildBans()` which inject these into the URI: https://github.com/DasWolke/SnowTransfer/blob/3187caf54df0c1c1b4cc9e03ba8d31c059b0947a/src/methods/Guilds.ts#L390-L392

I'm not sure if setting query strings directly in the URI is intended or not, especially with the current work regarding the built-in HTTP client?

*Marking the PR as draft because it doesn't fully fix the issue.*

**Comment by PapiOphidian** [comment]
Yeah I have no idea. I feel like I've been super inconsistent with that. It should at the very least map the params to the URL on non GET calls since it turns the body into the params if it's a GET request. As for the built in HTTP client, it might go on hold because I am not a pro with the HTTP syntax and I may just make a client wrapping around the built in http client or eventually put a peer dep on Node 18 for global.fetch versus centra

**Comment by PapiOphidian** [comment]
Sorry this took a bit. Holidays and birthdays got in the way. I ended up trying to avoid manually mapping the URLSearchParams manually and instead passing them to the built in query mapper centra has assuming the HTTP method was GET or matched a regex which was from legacy code base. Idk if still applicable.

Some routes still have limited manual mapping because of HTTP method and some of them use the URLSearchParams constructor, which hopefully is more likely to be covered by JIT.

> Actually, pagination on this endpoint seems to be broken since it was implemented (it throws a 404)
Was this from the fact that I did a dumb with qs mapping or was this a Discord issue even if the URL was correct?

**Comment by Zoddo** [comment]
> Was this from the fact that I did a dumb with qs mapping or was this a Discord issue even if the URL was correct?

It was an issue with the qs handling on SnowTransfer; the URL was invalid.

I'll try to update SnowTransfer again in the next week or so, and I'll immediately see if the issue is fixed :) 

Thanks!

**Pull request closed without merging**
